export const RESET = 'RESET'
// inputs
export const INPUT_CHANGE = 'INPUT_CHANGE'
// auth screen
export const AUTH_FORM_INPUT_CHANGE = 'AUTH_FORM_INPUT_CHANGE'
export const AUTH_FORM_RESET = 'AUTH_FORM_RESET'
// auth status
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS'
// quiz screen
export const SET_INFO_MESSAGE = 'SET_INFO_MESSAGE'
export const QUIZ_SET_SELECTED_OPTION = 'QUIZ_SET_SELECTED_OPTION'
export const SET_QUIZ = 'SET_QUIZ'
// add/edit question screen
export const QUESTION_FORM_RESET = 'QUESTION_FORM_RESET'
export const QUESTION_FORM_OPTION_DISTRACTOR_CHANGE = 'QUESTION_FORM_OPTION_DISTRACTOR_CHANGE'
export const QUESTION_FORM_OPTION_REMOVAL = 'QUESTION_FORM_OPTION_REMOVAL'
export const QUESTION_FORM_OPTION_ADDITION = 'QUESTION_FORM_OPTION_ADDITION'
export const QUESTION_FORM_SET_CORRECT_OPTION = 'QUESTION_FORM_SET_CORRECT_OPTION'
export const QUESTION_FORM_SET_EXISTING = 'QUESTION_FORM_SET_EXISTING'
// spinner
export const SPINNER_ON = 'SPINNER_ON'
export const SPINNER_OFF = 'SPINNER_OFF'
// quiz list
export const SET_ALL_QUIZZES = 'SET_ALL_QUIZZES'
// stats
export const SET_GENERAL_STATS = 'SET_GENERAL_STATS' // =============== 👉 [Code-Along 10.2] - step 2
